tareas/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('taskList', views.taskList, name='taskList'),
    path('addTask', views.addTask, name='addTask'),
]

todo/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    tarea = models.CharField(max_length=256)
    priority = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.id}: {self.tarea} the priority is {self.priority}"

todo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse


from .models import Task
# Create your views here.
   
class NewTaskForm(forms.Form):
    task = forms.CharField(label = "New task")
    priority = forms.CharField(label = "Priority", min_length= 1, max_length = 10)

def index(request):
    return HttpResponse("Hola mundo")

def taskList(request):
    return render(request, "tareas/listTask.html",{
        "tasks":Task.objects.all()
    })

def addTask(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data
            newTask = Task(tarea = task['task'], priority = task['priority'])
            newTask.save()
            return HttpResponseRedirect(reverse("tasks:taskList"))
    
    return render(request, "tareas/addTask.html",{
        "form":NewTaskForm()
    })

todo/templates/prueba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

todo/templates/tareas/addTask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NEW TASK</title>
</head>
<body>
    <h1>New task</h1>
    <form action="{% url 'tasks:addTask' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
</body>
</html>

todo/templates/tareas/listTask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LIST</title>
</head>
<body>
    <h1>TODO list</h1>
    <table border="1">
        <tr>
                <td>ID</td>
                <td>Task</td>
                <td>Priority</td>
        </tr>
            {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.tarea }}</td>
                <td>{{ task.priority }}</td>
            </tr>
            {% endfor %}
    </table>
</body>
</html>